version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: postgres_container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    hostname: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    
  # redis:
  #   image: redis:latest
  #   container_name: redis-container
  #   hostname: redis-container
  #   ports:
  #     - "6379:6379"
  #   # environment:
  #   #   REDIS_PASSWORD: your_password
  #   volumes:
  #      - redis_data:/data
  #   # command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  postgres_data: 
  pgadmin_data:
  # redis_data: